name: kagi_news
description: "A news client for Kite."
publish_to: 'none'

version: 1.0.3+3

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  equatable: ^2.0.7
  dio: ^5.8.0+1
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  intl: ^0.19.0
  flutter_markdown: ^0.7.7+1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/kite.svg
    - assets/dmf_logo.svg
    - assets/info.md
    - assets/acknowledgements.md
